<a href="https://colab.research.google.com/github/Nitish-Goyal/Pytorch-tutorial/blob/main/tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Mathematics operation

  * Addition, Subtraction, Multiplucation, Division, Remainder, Exponent
  * Shorthand and longhand
  * Reassignment

In [20]:
import torch
import numpy as np

In [21]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [22]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [23]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [25]:
# Subtraction function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [26]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [27]:
# Multiplication longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [28]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [29]:
# Division longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [30]:
# Remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [31]:
tensor_a

tensor([1, 2, 3, 4])

In [32]:
# Remainder longhand
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [33]:
# exponent / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [34]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [35]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [36]:
tensor_a

tensor([1, 2, 3, 4])

In [37]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
tensor_a

tensor([ 6,  8, 10, 12])

In [39]:
# tensor_a = tensor_a * tensor_b
tensor_a.mul_(tensor_b)

tensor([30, 48, 70, 96])

In [40]:
tensor_a

tensor([30, 48, 70, 96])

In [41]:
# tensor_a = tensor_b - tensor_a
tensor_a.sub_(tensor_b)

tensor([25, 42, 63, 88])

In [42]:
tensor_a

tensor([25, 42, 63, 88])

In [43]:
#tensor_a = tensor_b % tensor_a
tensor_a.remainder_(tensor_b)

tensor([0, 0, 0, 0])

In [44]:
tensor_b

tensor([5, 6, 7, 8])

In [45]:
tensor_a

tensor([0, 0, 0, 0])