<a href="https://colab.research.google.com/github/Nitish-Goyal/Pytorch-tutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor
 * A torch.Tensor is a multi-dimensional matrix containing element of a single data type.
 * Similar To Numpy array, but full of fun things that make the work better on GPU's(vs regular CPU's).
 * Defaut data type of float32
 * More suitable for deep learning than a numpy array

In [16]:
import torch
import numpy as np

List

In [17]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Array

In [18]:
np1 = np.random.rand(3)
np1

array([0.59782424, 0.78893392, 0.14132544])

In [19]:
np1.dtype

dtype('float64')

Tensor

In [20]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.7052, 0.6288, 0.4695, 0.4355],
        [0.0658, 0.8434, 0.0712, 0.9330],
        [0.6883, 0.6051, 0.6791, 0.0675]])

In [21]:
tensor_2d = torch.rand(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [22]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([0.5978, 0.7889, 0.1413], dtype=torch.float64)